### ISSUE TITLE
RuntimeError: expected scalar type float but found double

### ISSUE THREAD

**Issue by TaoTXiXi** [yformer/EfficientSAM#37]
When I run EfficientSAM_example.py file, a RuntimeError appears: expected scale type float but found double

**Comment by yformer** [comment]
@TaoTXiXi, can you share which line causes that issue?

**Comment by TaoTXiXi** [comment]
Sure, this is where the error occurred.
Traceback (most recent call last):
  File "G:/mycode/PythonCode/EfficientSAM-main/EfficientSAM_example.py", line 37, in <module>
    predicted_logits, predicted_iou = model(
  File "D:\software\Miniconda3\envs\myProject\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\mycode\PythonCode\EfficientSAM-main\efficient_sam\efficient_sam.py", line 207, in forward
    return self.predict_masks(
  File "G:\mycode\PythonCode\EfficientSAM-main\efficient_sam\efficient_sam.py", line 83, in predict_masks
    rescaled_batched_points = self.get_rescaled_pts(batched_points, input_h, input_w)
  File "G:\mycode\PythonCode\EfficientSAM-main\efficient_sam\efficient_sam.py", line 153, in get_rescaled_pts
    torch.where(
RuntimeError: expected scalar type float but found double.

**Comment by yformer** [comment]
@TaoTXiXi, we checked EfficientSAM_example.py works well from our side. Can you create a new virtual env to rerun it?

**Comment by hjinnkim** [comment]
Hello! I have encountered exactly same issue with @TaoTXiXi . I'm using conda environment with torch==1.11 with cuda==11.3.

If you don't mind, can you share your virtual environment configurations @yformer ?

**Comment by hjinnkim** [comment]
Never mind, I solved the problem after upgrading my torch version from 1.11 to 1.12.1. I think older versions of torch have error with torch.where function.

**Comment by hideinthesoul** [comment]
in efficient_sam.py, modify line 156 and 161:
`
    def get_rescaled_pts(self, batched_points: torch.Tensor, input_h: int, input_w: int):
        return torch.stack(
            [
                torch.where(
                    batched_points[..., 0] >= 0,
                    batched_points[..., 0] * self.image_encoder.img_size / input_w,
                    torch.tensor(-1.0, device=batched_points.device).float(), ### modify -1 to this
                ),
                torch.where(
                    batched_points[..., 1] >= 0,
                    batched_points[..., 1] * self.image_encoder.img_size / input_h,
                    torch.tensor(-1.0, device=batched_points.device).float(),  ### modify -1 to this
                ),
            ],
            dim=-1,
        )
`
